### ISSUE TITLE
Support for adding Markers

### ISSUE THREAD

**Issue by ericnation** [sakren/node-google-maps#9]
I can't get it to work with Markers.  Does this package have support for adding Markers? If yes, can you provide an example please?

**Comment by sakren** [comment]
Hello, currently there is only support for features I or someone else needed, so I have to say "no, it is not supported" ;-)

But pull requests are welcomed and appreciated. Or you can tell me what needs to be done and I can add it, unfortunately I don't have time right now, so I could do it next week.. In the best case

**Comment by ericnation** [comment]
Got it working! Thanks though. 

GoogleMapsLoader.load(function (google) {
      var myLatlng = new google.maps.LatLng(-34.397, 150.644);
      var mapOptions = {
        center: myLatlng,
        zoom: 15,
        zoomControl: true
      };

      var map = new google.maps.Map(el, mapOptions);

      new google.maps.Marker({
        position: myLatlng,
        map: map,
        title: 'Hello World!',
        animation: google.maps.Animation.DROP
      });
    });

**Comment by sakren** [comment]
Oh I see, so it works with loaded google object :-)

You see, this package is just some kind of "url builder for better loading of google object". Maybe I could use your code as an example in documentation.

**Comment by ericnation** [comment]
For sure.
